#!/usr/bin/env python3
"""Generate desktop/src/theme/generated.rs from the web app's theme sources.

Run from the repository root after changing app/globals.css or lib/theme.ts:

    python3 desktop/scripts/generate_themes.py && (cd desktop && cargo fmt)
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CSS = (ROOT / "app/globals.css").read_text()
THEME_TS = (ROOT / "lib/theme.ts").read_text()
OUTPUT = ROOT / "desktop/src/theme/generated.rs"

FIELDS = [
    "paper", "ink", "muted", "quiet", "line", "selection", "heading",
    "text-strong", "text-soft", "text-dim", "surface-input", "surface",
    "surface-raised", "surface-control", "surface-selected", "surface-hover",
    "border-subtle", "border", "border-strong", "focus", "primary", "primary-ink",
    "shadow", "subtle-highlight",
]


def block(selector):
    match = re.search(re.escape(selector) + r"\s*\{(.*?)\n\}", CSS, re.S)
    return dict(re.findall(r"--([a-z-]+):\s*([^;]+);", match.group(1)))


def color(value):
    value = value.strip()
    match = re.fullmatch(r"#([0-9a-fA-F]+)", value)
    if match:
        digits = match.group(1)
        if len(digits) == 3:
            digits = "".join(c * 2 for c in digits)
        return f"0x{digits.lower()}ff"
    match = re.fullmatch(r"rgba\(\s*(\d+),\s*(\d+),\s*(\d+),\s*([\d.]+)\s*\)", value)
    if match:
        r, g, b, a = (int(match[1]), int(match[2]), int(match[3]), float(match[4]))
        return f"0x{r:02x}{g:02x}{b:02x}{round(a * 255):02x}"
    raise SystemExit(f"unsupported colour: {value}")


def main():
    root = block(":root")
    themes = re.findall(
        r'id: "([^"]+)",\s*label: "([^"]+)",\s*detail: "([^"]+)",\s*colorScheme: "\w+",'
        r'\s*swatches: \["(#\w+)", "(#\w+)", "(#\w+)"\]',
        THEME_TS,
    )
    out = [
        "// Generated by desktop/scripts/generate_themes.py from app/globals.css and\n",
        "// lib/theme.ts. Do not edit by hand.\n",
        "use super::{Palette, ThemeDef, ThemeId};\n\n",
        "pub const THEMES: &[ThemeDef] = &[\n",
    ]
    for theme_id, label, detail, *swatches in themes:
        values = dict(root)
        if theme_id != "dark":
            values.update(block(f'html[data-theme="{theme_id}"]'))
        out.append("    ThemeDef {\n")
        out.append(f'        id: ThemeId("{theme_id}"),\n')
        out.append(f'        label: "{label}",\n')
        out.append(f'        detail: "{detail}",\n')
        out.append(f"        swatches: [{', '.join(color(s) for s in swatches)}],\n")
        out.append("        palette: Palette {\n")
        for field in FIELDS:
            out.append(f"            {field.replace('-', '_')}: {color(values[field])},\n")
        out.append("        },\n    },\n")
    out.append("];\n")
    OUTPUT.write_text("".join(out))
    print(f"wrote {len(themes)} themes to {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
